### ISSUE TITLE
Toggle to show Alt Art Cards

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#101] opened 2020-10-19 08:39 UTC
A user has requested that they should be allowed to add alternative artwork cards to their decks when building.

Maybe we can add some form of alternative artwork toggle? In the api, we would remove `&includeAliased=yes`

**Comment by FelixRilling** [comment] 2020-10-19 11:06
Duplicate of #70

**Closed by FelixRilling** 2020-10-19 11:06 UTC
Labels: duplicate, enhancement
